package com.web.dao;

import com.web.model.PComment;

public interface PCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    int insert(PComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    int insertSelective(PComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    PComment selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PComment record);
}