package com.web.dao;

import com.web.model.PNComment;

public interface PNCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long ncid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    int insert(PNComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    int insertSelective(PNComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    PNComment selectByPrimaryKey(Long ncid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PNComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_n_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PNComment record);
}