package com.web.dao;

import com.web.model.PNews;

public interface PNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    int insert(PNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    int insertSelective(PNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    PNews selectByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_news
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PNews record);
}