package com.web.dao;

import com.web.model.PPlugins;

public interface PPluginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    int insert(PPlugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    int insertSelective(PPlugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    PPlugins selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PPlugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_plugins
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PPlugins record);
}