package com.web.dao;

import com.web.model.PSlqLog;

public interface PSlqLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    int insert(PSlqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    int insertSelective(PSlqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    PSlqLog selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PSlqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_slq_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PSlqLog record);
}