package com.web.dao;

import com.web.model.PUsers;

import java.util.List;

public interface PUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    int insert(PUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    int insertSelective(PUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    PUsers selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PUsers record);

    List<PUsers> getUsersList(PUsers record);
    PUsers getUsers(PUsers pUsers);
}