package com.web.model;

import java.util.Date;

public class PComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.tId
     *
     * @mbg.generated
     */
    private Long tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.pId
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.pName
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.uId
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.uName
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.line
     *
     * @mbg.generated
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.rete
     *
     * @mbg.generated
     */
    private String rete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_comment.newDate
     *
     * @mbg.generated
     */
    private Date newdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.tId
     *
     * @return the value of p_comment.tId
     *
     * @mbg.generated
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.tId
     *
     * @param tid the value for p_comment.tId
     *
     * @mbg.generated
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.pId
     *
     * @return the value of p_comment.pId
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.pId
     *
     * @param pid the value for p_comment.pId
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.pName
     *
     * @return the value of p_comment.pName
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.pName
     *
     * @param pname the value for p_comment.pName
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.uId
     *
     * @return the value of p_comment.uId
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.uId
     *
     * @param uid the value for p_comment.uId
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.uName
     *
     * @return the value of p_comment.uName
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.uName
     *
     * @param uname the value for p_comment.uName
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.line
     *
     * @return the value of p_comment.line
     *
     * @mbg.generated
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.line
     *
     * @param line the value for p_comment.line
     *
     * @mbg.generated
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.rete
     *
     * @return the value of p_comment.rete
     *
     * @mbg.generated
     */
    public String getRete() {
        return rete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.rete
     *
     * @param rete the value for p_comment.rete
     *
     * @mbg.generated
     */
    public void setRete(String rete) {
        this.rete = rete == null ? null : rete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.body
     *
     * @return the value of p_comment.body
     *
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.body
     *
     * @param body the value for p_comment.body
     *
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_comment.newDate
     *
     * @return the value of p_comment.newDate
     *
     * @mbg.generated
     */
    public Date getNewdate() {
        return newdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_comment.newDate
     *
     * @param newdate the value for p_comment.newDate
     *
     * @mbg.generated
     */
    public void setNewdate(Date newdate) {
        this.newdate = newdate;
    }
}