package com.web.model;

import java.util.Date;

public class PLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.log_id
     *
     * @mbg.generated
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.methotName
     *
     * @mbg.generated
     */
    private String methotname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.oprationType
     *
     * @mbg.generated
     */
    private String oprationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.visitData
     *
     * @mbg.generated
     */
    private Date visitdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.respDate
     *
     * @mbg.generated
     */
    private Date respdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.errorMsg
     *
     * @mbg.generated
     */
    private String errormsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_log.reaults
     *
     * @mbg.generated
     */
    private String reaults;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.log_id
     *
     * @return the value of p_log.log_id
     *
     * @mbg.generated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.log_id
     *
     * @param logId the value for p_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.methotName
     *
     * @return the value of p_log.methotName
     *
     * @mbg.generated
     */
    public String getMethotname() {
        return methotname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.methotName
     *
     * @param methotname the value for p_log.methotName
     *
     * @mbg.generated
     */
    public void setMethotname(String methotname) {
        this.methotname = methotname == null ? null : methotname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.oprationType
     *
     * @return the value of p_log.oprationType
     *
     * @mbg.generated
     */
    public String getOprationtype() {
        return oprationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.oprationType
     *
     * @param oprationtype the value for p_log.oprationType
     *
     * @mbg.generated
     */
    public void setOprationtype(String oprationtype) {
        this.oprationtype = oprationtype == null ? null : oprationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.visitData
     *
     * @return the value of p_log.visitData
     *
     * @mbg.generated
     */
    public Date getVisitdata() {
        return visitdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.visitData
     *
     * @param visitdata the value for p_log.visitData
     *
     * @mbg.generated
     */
    public void setVisitdata(Date visitdata) {
        this.visitdata = visitdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.respDate
     *
     * @return the value of p_log.respDate
     *
     * @mbg.generated
     */
    public Date getRespdate() {
        return respdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.respDate
     *
     * @param respdate the value for p_log.respDate
     *
     * @mbg.generated
     */
    public void setRespdate(Date respdate) {
        this.respdate = respdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.userId
     *
     * @return the value of p_log.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.userId
     *
     * @param userid the value for p_log.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.params
     *
     * @return the value of p_log.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.params
     *
     * @param params the value for p_log.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.errorMsg
     *
     * @return the value of p_log.errorMsg
     *
     * @mbg.generated
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.errorMsg
     *
     * @param errormsg the value for p_log.errorMsg
     *
     * @mbg.generated
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_log.reaults
     *
     * @return the value of p_log.reaults
     *
     * @mbg.generated
     */
    public String getReaults() {
        return reaults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_log.reaults
     *
     * @param reaults the value for p_log.reaults
     *
     * @mbg.generated
     */
    public void setReaults(String reaults) {
        this.reaults = reaults == null ? null : reaults.trim();
    }
}