package com.web.model;

import java.util.Date;

public class PNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.nId
     *
     * @mbg.generated
     */
    private Integer nid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.nTitle
     *
     * @mbg.generated
     */
    private String ntitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.nWriter
     *
     * @mbg.generated
     */
    private String nwriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.nDate
     *
     * @mbg.generated
     */
    private Date ndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.uID
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.uName
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_news.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.nId
     *
     * @return the value of p_news.nId
     *
     * @mbg.generated
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.nId
     *
     * @param nid the value for p_news.nId
     *
     * @mbg.generated
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.nTitle
     *
     * @return the value of p_news.nTitle
     *
     * @mbg.generated
     */
    public String getNtitle() {
        return ntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.nTitle
     *
     * @param ntitle the value for p_news.nTitle
     *
     * @mbg.generated
     */
    public void setNtitle(String ntitle) {
        this.ntitle = ntitle == null ? null : ntitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.nWriter
     *
     * @return the value of p_news.nWriter
     *
     * @mbg.generated
     */
    public String getNwriter() {
        return nwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.nWriter
     *
     * @param nwriter the value for p_news.nWriter
     *
     * @mbg.generated
     */
    public void setNwriter(String nwriter) {
        this.nwriter = nwriter == null ? null : nwriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.nDate
     *
     * @return the value of p_news.nDate
     *
     * @mbg.generated
     */
    public Date getNdate() {
        return ndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.nDate
     *
     * @param ndate the value for p_news.nDate
     *
     * @mbg.generated
     */
    public void setNdate(Date ndate) {
        this.ndate = ndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.uID
     *
     * @return the value of p_news.uID
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.uID
     *
     * @param uid the value for p_news.uID
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.uName
     *
     * @return the value of p_news.uName
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.uName
     *
     * @param uname the value for p_news.uName
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_news.body
     *
     * @return the value of p_news.body
     *
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_news.body
     *
     * @param body the value for p_news.body
     *
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }
}