package com.web.model;

import java.util.Date;

public class PPlugins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pId
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pName
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pWriter
     *
     * @mbg.generated
     */
    private String pwriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pSyno
     *
     * @mbg.generated
     */
    private String psyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pUploadId
     *
     * @mbg.generated
     */
    private Long puploadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pUploadName
     *
     * @mbg.generated
     */
    private String puploadname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pUpTime
     *
     * @mbg.generated
     */
    private Date puptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pEdit
     *
     * @mbg.generated
     */
    private String pedit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pSoft
     *
     * @mbg.generated
     */
    private String psoft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pSoftEdit
     *
     * @mbg.generated
     */
    private String psoftedit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pRete
     *
     * @mbg.generated
     */
    private String prete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_plugins.pAddress
     *
     * @mbg.generated
     */
    private String paddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pId
     *
     * @return the value of p_plugins.pId
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pId
     *
     * @param pid the value for p_plugins.pId
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pName
     *
     * @return the value of p_plugins.pName
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pName
     *
     * @param pname the value for p_plugins.pName
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pWriter
     *
     * @return the value of p_plugins.pWriter
     *
     * @mbg.generated
     */
    public String getPwriter() {
        return pwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pWriter
     *
     * @param pwriter the value for p_plugins.pWriter
     *
     * @mbg.generated
     */
    public void setPwriter(String pwriter) {
        this.pwriter = pwriter == null ? null : pwriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pSyno
     *
     * @return the value of p_plugins.pSyno
     *
     * @mbg.generated
     */
    public String getPsyno() {
        return psyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pSyno
     *
     * @param psyno the value for p_plugins.pSyno
     *
     * @mbg.generated
     */
    public void setPsyno(String psyno) {
        this.psyno = psyno == null ? null : psyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pUploadId
     *
     * @return the value of p_plugins.pUploadId
     *
     * @mbg.generated
     */
    public Long getPuploadid() {
        return puploadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pUploadId
     *
     * @param puploadid the value for p_plugins.pUploadId
     *
     * @mbg.generated
     */
    public void setPuploadid(Long puploadid) {
        this.puploadid = puploadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pUploadName
     *
     * @return the value of p_plugins.pUploadName
     *
     * @mbg.generated
     */
    public String getPuploadname() {
        return puploadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pUploadName
     *
     * @param puploadname the value for p_plugins.pUploadName
     *
     * @mbg.generated
     */
    public void setPuploadname(String puploadname) {
        this.puploadname = puploadname == null ? null : puploadname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pUpTime
     *
     * @return the value of p_plugins.pUpTime
     *
     * @mbg.generated
     */
    public Date getPuptime() {
        return puptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pUpTime
     *
     * @param puptime the value for p_plugins.pUpTime
     *
     * @mbg.generated
     */
    public void setPuptime(Date puptime) {
        this.puptime = puptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pEdit
     *
     * @return the value of p_plugins.pEdit
     *
     * @mbg.generated
     */
    public String getPedit() {
        return pedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pEdit
     *
     * @param pedit the value for p_plugins.pEdit
     *
     * @mbg.generated
     */
    public void setPedit(String pedit) {
        this.pedit = pedit == null ? null : pedit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pSoft
     *
     * @return the value of p_plugins.pSoft
     *
     * @mbg.generated
     */
    public String getPsoft() {
        return psoft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pSoft
     *
     * @param psoft the value for p_plugins.pSoft
     *
     * @mbg.generated
     */
    public void setPsoft(String psoft) {
        this.psoft = psoft == null ? null : psoft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pSoftEdit
     *
     * @return the value of p_plugins.pSoftEdit
     *
     * @mbg.generated
     */
    public String getPsoftedit() {
        return psoftedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pSoftEdit
     *
     * @param psoftedit the value for p_plugins.pSoftEdit
     *
     * @mbg.generated
     */
    public void setPsoftedit(String psoftedit) {
        this.psoftedit = psoftedit == null ? null : psoftedit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pRete
     *
     * @return the value of p_plugins.pRete
     *
     * @mbg.generated
     */
    public String getPrete() {
        return prete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pRete
     *
     * @param prete the value for p_plugins.pRete
     *
     * @mbg.generated
     */
    public void setPrete(String prete) {
        this.prete = prete == null ? null : prete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_plugins.pAddress
     *
     * @return the value of p_plugins.pAddress
     *
     * @mbg.generated
     */
    public String getPaddress() {
        return paddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_plugins.pAddress
     *
     * @param paddress the value for p_plugins.pAddress
     *
     * @mbg.generated
     */
    public void setPaddress(String paddress) {
        this.paddress = paddress == null ? null : paddress.trim();
    }
}