package com.web.model;

public class PUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uName
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uPawd
     *
     * @mbg.generated
     */
    private String upawd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uPhone
     *
     * @mbg.generated
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uEmail
     *
     * @mbg.generated
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uLevel
     *
     * @mbg.generated
     */
    private String ulevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_users.uScore
     *
     * @mbg.generated
     */
    private String uscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uid
     *
     * @return the value of p_users.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uid
     *
     * @param uid the value for p_users.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uName
     *
     * @return the value of p_users.uName
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uName
     *
     * @param uname the value for p_users.uName
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uPawd
     *
     * @return the value of p_users.uPawd
     *
     * @mbg.generated
     */
    public String getUpawd() {
        return upawd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uPawd
     *
     * @param upawd the value for p_users.uPawd
     *
     * @mbg.generated
     */
    public void setUpawd(String upawd) {
        this.upawd = upawd == null ? null : upawd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uPhone
     *
     * @return the value of p_users.uPhone
     *
     * @mbg.generated
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uPhone
     *
     * @param uphone the value for p_users.uPhone
     *
     * @mbg.generated
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uEmail
     *
     * @return the value of p_users.uEmail
     *
     * @mbg.generated
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uEmail
     *
     * @param uemail the value for p_users.uEmail
     *
     * @mbg.generated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uLevel
     *
     * @return the value of p_users.uLevel
     *
     * @mbg.generated
     */
    public String getUlevel() {
        return ulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uLevel
     *
     * @param ulevel the value for p_users.uLevel
     *
     * @mbg.generated
     */
    public void setUlevel(String ulevel) {
        this.ulevel = ulevel == null ? null : ulevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_users.uScore
     *
     * @return the value of p_users.uScore
     *
     * @mbg.generated
     */
    public String getUscore() {
        return uscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_users.uScore
     *
     * @param uscore the value for p_users.uScore
     *
     * @mbg.generated
     */
    public void setUscore(String uscore) {
        this.uscore = uscore == null ? null : uscore.trim();
    }
}